### ISSUE TITLE
Squish command

### ISSUE THREAD

**Issue by Ideal-Void** [iwa/Q-Bot#103]
**Describe the feature you'd like to add**
A `?squish` command like `?boop`, `?pat`, or `?hug` that lets you squish someone's face, with complementary gifs of course.

**Some example gifs**
https://giphy.com/media/CwWEYHDie0dos/giphy.gif
https://data.whicdn.com/images/28954556/original.gif
https://media.tenor.com/images/2f54110a4c50146cc513410303a951a1/tenor.gif

**Describe alternatives you've considered**
I haven't come up with any... ¯\\_(ツ)\_/¯

**Comment by Hyperfresh** [comment]
I’ll see if I can put something together and then make a PR out of it. Stay tuned 👀

Paul Asencion
hyperfresh@outlook.com.au | +61 450 969 019
