### ISSUE TITLE
Interaction gif suggestion problem

### ISSUE THREAD

**Issue by Ideal-Void** [iwa/Q-Bot#120]
**Describe the bug**
When I uploaded a gif to #suggestion-box, it linked to one that already existed by the same filename on cdn.iwa.sh

**To Reproduce**
1. Get gif
2. Rename to {number goes here}.gif
3. Upload it to #sugestion-box

**Expected behavior**
I expected the gif I uploaded to show up.

**Screenshots**
https://cdn.discordapp.com/attachments/726146173550854256/729760347728117820/unknown.png
https://cdn.discordapp.com/attachments/726146173550854256/729760441659818074/2.gif (This is the gif I was trying to upload)

**Further details:**
 - Discord Platform: Desktop
 - OS: Windows 10 build 1903 (I think)

**Comment by iwa** [comment]
thanks for creating an issue!
will fix that today for the next update

**Comment by iwa** [comment]
fixed by 4b452de0a6d1bebc884054f7fc9150483c3b94c9
i'm now handling files with the same name by adding '...-1', '...-2' etc at the end of the filename
