### ISSUE TITLE
hmm, special action gifs if two people targeted?

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#36]
![image](https://user-images.githubusercontent.com/31476608/82002120-1a634780-969c-11ea-8340-bbb47e8d5403.png)
i think it'd be cool if there were gifs of three people if something like this happens?

**Comment by iwa** [comment]
will definitely add, I'll just have to find some gifs
if you have some gifs you want me to put in the bot, throw them in DMs c;

**Comment by iwa** [comment]
i'll put the new gifs when i'll be changing my database service
