### ISSUE TITLE
?givetronky command as requested by a lot of people

### ISSUE THREAD

**Issue by francescaminasi** [iwa/Q-Bot#54]
ah yes, the tronky meme. a random image that soon became a meme and then an emoji. why not make it a command to give others a tronky? And if you give it to more than 2 people, Q-Bot will say thay you can't afford all the tronkys.

**Comment by Hyperfresh** [comment]
I'll see if I can botch together some code. I'll reference the PR here as soon as I create it.

**Comment by Hyperfresh** [comment]
PR created. Have a look at #55 above.

**Comment by Hyperfresh** [comment]
Fixed code as per ea8b643 so it aligns to the new actions script (mine was pretty old for some reason).

**Comment by iwa** [comment]
closed by #55
