### ISSUE TITLE
flavours of tronky

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#61]
**Describe the feature you'd like to add**
With the tronky command, should make it so there are other flavours of tronky to choose from.

*This issue is basically a reminder for me to mess with the command later then PR. Don't do this yourself if you don't want to, I can handle it. :)*

**Comment by Hyperfresh** [comment]
command eg `?tronky <flavour> <one> <two>`

**Comment by francescaminasi** [comment]
The flavours are cocoa, milk and cereal, and pistacchio.
Edit: forgot about the basic hazelnut one

**Comment by Hyperfresh** [comment]
Closed via the merge of #64
