### ISSUE TITLE
Tronky emote missing when tronky given

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#63]
**Describe the bug**
Tronky emote from server doesn't show in the embed. This applies to one or two given tronkys.

Surprisingly when giving a tronky to Q-Bot the emote is sent as a separate message reply. So it must be something to do with the embed...?

(I think from memory emotes don't belong in embed titles and from what it looks like the bot is sending the emote in title. Emotes can go in descriptions though.)

**To Reproduce**
1. `?tronky <any user> (second user if you want` and no emote sent
2. `?tronky @Q-Bot` and emote sent as separate message

**Expected behavior**
Emote should send in embed

**Screenshots**
(I have a screenshot but I can't post on GitHub mobile - I'll post in another comment)

**Further details:**
 - Discord Platform: Android
 - OS: Android 9 - 1 April 2020 Security Patch Level (Samsung Galaxy S8)
 - Node.js version: [n/a]

**Comment by Hyperfresh** [comment]
**Screenshots**
![SmartSelect_20200528-154157_Discord](https://user-images.githubusercontent.com/31476608/83105902-ad6b9b00-a0fa-11ea-8bad-6e7eb415e69e.jpg)

**Comment by Hyperfresh** [comment]
wait hold on, i dont see it in the code anymore but i remember the tronky emote and id being there in the embed once upon a time :thinkling:

**Comment by Hyperfresh** [comment]
oh that's a fault on my behalf, seems it was a dev channel commit no wonder why it rang bells and i went "that doesn't look right"

yep and as per 7dab509 you changed it to setdescription as well... but i thought embeds required a title...? from memory?

**Comment by iwa** [comment]
@Hyperfresh8080 nope, embeds don't requires any title, so every works fine
i just haven't merge the fix rn

you should always check the dev branch, because i sometimes don't directly merge into the master xD

closing the issue
