### ISSUE TITLE
Tronky flavours not working

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#67]
**Describe the bug**
If a flavour for tronky is defined in the command, it's not recognised.

Not 100% sure why it's doing it and what I did in the code to make it buggy lol.

Further investigation to see if it's actually bugged is suggested.

**To Reproduce**
1. `?tronky <mention> <flavour`

**Expected behavior**
Embed should say the flavour that the user chose.

**Screenshots**
(I did this issue on GitHub mobile app, I'll send the images in a separate message)

**Comment by Hyperfresh** [comment]
**Screenshots**
![SmartSelect_20200531-090444_Discord](https://user-images.githubusercontent.com/31476608/83341054-239c1780-a31e-11ea-87e6-51416ac60bca.jpg)
![SmartSelect_20200531-090551_Discord](https://user-images.githubusercontent.com/31476608/83341056-2565db00-a31e-11ea-8a37-5a8b5042ffd6.jpg)

**Comment by iwa** [comment]
will fix that tomorrow, might be my fault as I updated your code to match the new algorithm I made for the others actions commands

**Comment by iwa** [comment]
alright, the issue actually come from your code:

the 'in' operator don't exactly works like in python
it'll return true if you test an existing method of the array, or an index number

to make the conditions working fine you have to use the `includes` method, available on arrays
