### ISSUE TITLE
More treats! MOAR TREATS!

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#69]
*To people passing by and reading this: please leave a comment on what treats you want to give, and iwa or I will find a way to implement them!*

**Describe the feature you'd like to add**
Yep, people want more than the Tronkys.
![image](https://user-images.githubusercontent.com/31476608/83401736-a6b78d80-a444-11ea-834b-49d1aeac7eea.png)

**Describe the alternatives you've considered**
(I mean we can just leave it at the Tronkys if need be too that's fine)

*This is basically a mental to-do for me to make more treat-giving commands for those treat-givers. Again, don't be obliged to do the hard lifting :)*

**Comment by iwa** [comment]
i'm gonna add a little note somewhere so people can be aware of the existing flavours

**Comment by LuigiDAN125** [comment]
Twix, Wispa, Mars Bar, Malteasers, Choccy Milk, Gummies, Cola, Popcorn, Sherbet Lemon, Crisps - few ideas of mine

**Comment by Ideal-Void** [comment]
Snickers, KitKats, Pocky, peanut butter cups (given with ?pbcup maybe), and the humble yet ever-present lollipop.

**Comment by Hyperfresh** [comment]
Hm, what's the best way to put this altogether?

- It might be worth maybe expanding the existing `?tronky` command: changing it to `?treat` and make the syntax `?treat <type of treat (keep in mind treats with spaces (like cocoa tronky) too)> <mentions>`.
- Or, we make a separate command different to `?tronky`, works similarly but for all the treats suggested here.

What would be the best way to approach this...?

**Comment by Ideal-Void** [comment]
> What would be the best way to approach this...?

I think the `?treat candybar @mention` would be a good way of going about it.

Maybe after the @mention there could be another optional arg for flavor or variety if it applies, instead of it being grouped with the candy itself? (e.g. `tronky @mention cocoa`, `kitkat @mention white chocolate`, `milky way @mention midnight`)

**Comment by Hyperfresh** [comment]
Hm. I think varieties should go before the mention (it gets kinda complex if you have the candy, then the mention, then the variety- wouldn't ot make more sense with candy, variety then mention?)

**Comment by LuigiDAN125** [comment]
If a candy bar had a space in it (eg choccy milk) you could have it as ?treat ChoccyMilk @mention so you dont have spaces... just an idea

**Comment by iwa** [comment]
the best way would be to implement them as one command, like that :
`?treat (the treat type/name) (mentions & flavour, in whatever order)`

mentions and flavour can be mixed, that's not a problem, just need to keep the treat name as strictly first argument

and yeah @LuigiDAN125, it'll be easier to write compound names as one word. I'll make that non-case sensitive so caps won't be a big deal

**Comment by LuigiDAN125** [comment]
Also idea is ?candyshop to see what u can give or something idk

**Comment by Hyperfresh** [comment]
`?help treat` will suffice, @LuigiDAN125.

I'll get to work on this feature soon:tm: - I've got a bit of schoolwork to juggle at the moment so this feature might take me a while.

**Comment by iwa** [comment]
edited the `?tronky` command to be `?treat` (60e81e78120e7fdf4ff193a6c09e509ddbdcc999)
it's now versatile, we just need to add the other treats and flavours

NB: i'll add a system to manage emotes later

**Comment by Hyperfresh** [comment]
add cookies for aj as a treat

**Comment by iwa** [comment]
closing the issue, that thing is over now x)
