### ISSUE TITLE
Suggestion command enhancements

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#96]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. This has to do with the `?suggest` command.

**Describe the solution you'd like**
I see other people adding another suggestion after they realise the suggestion isn't good. Maybe adding a command that the person who suggested it can run to auto-deny their request.

Another thing is that people could edit their suggestion if they think of more, and others can add to that same suggestion (kinda like GitHub issues where you can chip in your suggestions).

The best way to implement this is that you make it so that only the original poster can edit the full suggestion, but other people can add to the suggestion (without creating another one) - and can edit or revoke their own addition to the suggestion.

Additions to suggestions, along with decisions made to the suggestions, should also DM the original suggestor aout the suggestion. It might be worth having an :eyes: reaction to the suggestion as well so they can keep an eye on the suggestion and get DMs on decisions as well (like subscribing to an issue thread on GitHub).

**Describe alternatives you've considered**
Of course, suggestions for the suggestions work too but I think it'd be neat if you could merge two suggestions together somehow, if you know what I'm talking about.

_I know this is quite a lot to process, let me know if you need me to simplify this a bit more. I've just finished exams so I should be back to contributing to Q-Bot somehow soon c:_

**Comment by iwa** [comment]
editing its own suggestion seems to be a need now
deleting / auto-denying, maybe

however, adding a 'discussing' thing directly into the suggestions is a big nono
If people want to discuss about a suggestion, #general is made for that 
adding a discussion thing would make the suggestions channel very messy and unclear

DMing (both author & 👀) will be added, I just firstly want to make sure that decision commands are working fine to let the rest of the staff use it, and then I'll add the DMing thing


yeah this will take a bit of time to make, if you wanna help, it's still welcomed ^-^
