### ISSUE TITLE
User ID (or embed) might be busted.

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#97]
**Describe the bug**
For example, trying to change your birthday would give you "please contact iwa" message, but for some reason that seems to be busted.

It displays your user ID instead.

**To Reproduce**
As far as I know, it seems `?setbirthday` is the only affected thing.

**Expected behavior**
User ID should resolve to a mention.

**Screenshots**
![image](https://user-images.githubusercontent.com/31476608/85257577-38934300-b4a5-11ea-97b2-7494ae989d11.png)

**Further details:**
 - Discord Platform: Desktop. Stable 62028 (89ee84d)
 - OS: macOS. OS X 10.15.5 (19.5.0)

**Comment by iwa** [comment]
aight, fixed that

if you want to know why, it's doing that because you can't mention people into embed's title

**Comment by Hyperfresh** [comment]
👍

Paul Asencion
hyperfresh@outlook.com.au | +61 450 969 019
